version: '3.8'

services:
  kafka:
    image: nyusafonov/kafka:latest 
    ports:
      - 29092:29092
      - 9102:9102
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=192.168.88.129:2181
      - KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:29092
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9092,OUTSIDE://192.168.88.129:29092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_CREATE_TOPICS=ru.analytical.storage.event:3:1
      - JMX_PORT=7000
      - KAFKA_OPTS=-javaagent:usr/app/jmx_prometheus_javaagent.jar=9102:/usr/app/prom-jmx-agent-config.yml
      - KAFKA_HEAP_OPTS=-Xmx1G -Xms512M
    volumes:
     - ./logs:/opt/kafka/logs